### ISSUE TITLE
Localization (Multiple language)

### ISSUE THREAD

**Issue by doniwirawan** [OpenProjects-id/KawanData#8]
Don't you have a plan to make it more accessible for everyone at least to understand our mission on this website by making a localization for another language such a english?

**Comment by algonacci** [comment]
Actually in the early stage we are targeting for the local Indonesia people and make all the website pages using Indonesian so that people will have no entry barriers with the language.

But yes, we'll make the localization so people around the world can enjoy this platform and also contribute. 

Btw, thanks for the advice.

**Comment by algonacci** [comment]
This issue will be considered when KawanData have members and ready to expandt o make it more accessible for everyone.

For this time, I'll close this issue.
